/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateContentTypeArgs } from "./CreateContentTypeArgs";
import { UpdateContentTypeArgs } from "./UpdateContentTypeArgs";
import { DeleteContentTypeArgs } from "./DeleteContentTypeArgs";
import { ContentTypeFindManyArgs } from "./ContentTypeFindManyArgs";
import { ContentTypeFindUniqueArgs } from "./ContentTypeFindUniqueArgs";
import { ContentType } from "./ContentType";
import { ContentFindManyArgs } from "../../content/base/ContentFindManyArgs";
import { Content } from "../../content/base/Content";
import { ContentTypeService } from "../contentType.service";

@graphql.Resolver(() => ContentType)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ContentTypeResolverBase {
  constructor(
    protected readonly service: ContentTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "read",
    possession: "any",
  })
  async _contentTypesMeta(
    @graphql.Args() args: ContentTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ContentType])
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "read",
    possession: "any",
  })
  async contentTypes(
    @graphql.Args() args: ContentTypeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContentType[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ContentType",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ContentType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "read",
    possession: "own",
  })
  async contentType(
    @graphql.Args() args: ContentTypeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContentType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ContentType",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ContentType)
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "create",
    possession: "any",
  })
  async createContentType(
    @graphql.Args() args: CreateContentTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContentType> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ContentType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ContentType"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ContentType)
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "update",
    possession: "any",
  })
  async updateContentType(
    @graphql.Args() args: UpdateContentTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContentType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ContentType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ContentType"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ContentType)
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "delete",
    possession: "any",
  })
  async deleteContentType(
    @graphql.Args() args: DeleteContentTypeArgs
  ): Promise<ContentType | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Content])
  @nestAccessControl.UseRoles({
    resource: "ContentType",
    action: "read",
    possession: "any",
  })
  async contents(
    @graphql.Parent() parent: ContentType,
    @graphql.Args() args: ContentFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Content[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Content",
    });
    const results = await this.service.findContents(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
